# Generated by Django 5.2.11 on 2026-02-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
